sampling_time: 0.0
refresh_rate: 0.1
output_name: virtual_daq
instruments:
  virtual_device:
    type: virtual
    measurements:
      temperature:
        unit: celsius
        name: Temperature
        value: 25.0
      voltage:
        unit: volt
        name: Voltage
        value: 10.0
