sampling_time: 0.0
refresh_rate: 0.0
output_name: dmm6500_daq
instruments:
  dmm6500:
    type: multimeter
    make: generic_scpi
    model: SCPIMultimeter
    comm:
      type: file
      args:
        filename: /dev/usbtmc0
    measurements:
      current:
        quantity: current_dc
        unit: nanoamp
        name: Current
