sampling_time: 0.0
refresh_rate: 0.1
output_name: virtual_daq
instruments:
  virtual_temp:
    type: virtual
    measurements:
      temperature:
        quantity: value
        unit: celsius
        name: Temperature
        value: 25.0
  virtual_voltage:
    type: virtual
    measurements:
      voltage:
        quantity: value
        unit: volt
        name: Voltage
        value: 10.0
