sampling_time: 0.0
refresh_rate: 0.0
output_name: beercooler_daq
instruments:
instruments:
  keithley6485:
    type: instrument
    make: keithley
    model: Keithley6485
    comm:
      type: serial
      args:
        port: /dev/ttyKeithley6485
        baud: 9600
    measurements:
      current:
        quantity: current_dc
        unit: nanoamp
        name: Current
  dmm6500:
    type: multimeter
    make: generic_scpi
    model: SCPIMultimeter
    comm:
      type: file
      args:
        filename: /dev/usbtmc1
    measurements:
      current:
        quantity: voltage_dc
        unit: volt
        name: Voltage
  fluke3000:
    type: multimeter
    make: fluke
    model: Fluke3000
    comm:
      type: serial
      args:
        port: /dev/ttyFluke3000
        baud: 115200
    measurements:
      temperature:
        quantity: temperature
        unit: celsius
        name: Temperature
  glassmanfr:
    type: power_supply
    make: glassman
    model: GlassmanFR
    controls: ['voltage', 'current']
    comm:
      type: serial
      args:
        port: /dev/ttyGlassmanFR
        baud: 9600
    measurements:
      voltage:
        quantity: voltage
        unit: volt
        name: PSU Voltage
        value: 0.0
      voltage_sense:
        quantity: voltage_sense
        unit: volt
        name: PSU Sense Voltage
      current:
        quantity: current
        unit: amp
        name: PSU Current
        value: 0.001
      current_sense:
        quantity: current_sense
        unit: amp
        name: PSU Sense Current
