sampling_time: 0.0
refresh_rate: 0.0
output_name: glassmanfr_daq
instruments:
  glassmanfr:
    type: power_supply
    make: glassman
    model: GlassmanFR
    comm: serial
    comm_args:
      port: /dev/ttyUSB0
      baud: 9600
    measurements:
      voltage:
        quantity: voltage
        unit: volt
        name: PSU Voltage
        value: 100.0
      voltage_sense:
        quantity: voltage_sense
        unit: volt
        name: PSU Sense Voltage
      current:
        quantity: current
        unit: amp
        name: PSU Current
        value: 0.001
      current_sense:
        quantity: current_sense
        unit: amp
        name: PSU Sense Current
